# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import os
import sys
sys.path.insert(0, os.path.abspath('./_custom_extensions'))


# -- Project information -----------------------------------------------------

project = 'Gamepad.Coder\'s'
copyright = 'Gamepad.Coder 2021'
author = 'Gamepad.Coder'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = '2021'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'extended_ahk_lexer',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'Documentation'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = 'sphinx'
# pygments_style = None

#                                      rank                bg
#                                  ============       =============
# pygments_style = 'default'
# pygments_style = 'emacs'            # *               white
# pygments_style = 'colorful'         #                 white
# pygments_style = 'autumn'           #                 white
# pygments_style = 'murphy'           #                 white
# pygments_style = 'pastie'           #                 white
# pygments_style = 'borland'          #                 white
# pygments_style = 'trac'             #                 white
# pygments_style = 'bw'               #                 white
# pygments_style = 'vs'               #                 white
# pygments_style = 'xcode'            #                 white
# pygments_style = 'igor'             #                 white
# pygments_style = 'lovelace'         #                 white
# pygments_style = 'algol'            #                 white
# pygments_style = 'algol_nu'         #                 white
# pygments_style = 'arduino'          #                 white
# pygments_style = 'rainbow_dash'     #                 white
# pygments_style = 'abap'             #                 white
# pygments_style = 'perldoc'          #               tan
# pygments_style = 'paraiso-light'    #               tan
# pygments_style = 'friendly'         # *             grey
# pygments_style = 'manni'            #               grey
# pygments_style = 'tango'            #               grey
# pygments_style = 'fruity'           #             night
# pygments_style = 'vim'              #             night
# pygments_style = 'rrt'              #             night
# pygments_style = 'paraiso-dark'     #             night
# pygments_style = 'native'           # ***         night
                                          # good support for if else winget substr

#------------------------------------------------------------------------------------
# HOW TO CUSTOMIZE LEXER : 
#------------------------------------------------------------------------------------
#  1) Spend many hours Googling with no recipes that will take less than a day to learn
#  2) Prepare to give up
#  3) Finally find a blog entry which mentions Sphinx's
#     built-in functionality to easily import a lexer : 
#  4) Write lexer
#  5) Set `pygments_style = 'monokai'
#  6) Download Pygments source code 
#  7) Navigate to ../Pygments-2.8.1/pygments/styles/monokai.py
#  8) Observe that unaffected keywords are still given a unique span class
#  9) Write simple css to color the keywords of your language defined in (4)
#------------------------------------------------------------------------------------
#  Magical URL :    https://samprocter.com/2014/06/documenting-a-language-using-a-custom-sphinx-domain-and-pygments-lexer/
#------------------------------------------------------------------------------------
pygments_style = 'monokai'          # ***         night

# highlight_language = 'autohotkey'
highlight_language = 'autohotkey'
# highlight_language = 'pygments.lexers.automation.AutohotkeyLexer'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = 'sphinx_rtd_theme'


html_theme = 'sphinx_rtd_theme__modified'
html_theme_path = ["."]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme_options = {
    # 'sticky_navigation': False
    
    #  Only display the logo image, do not display the project name at the top of the sidebar
    # 'logo_only' : False,
    # 'show_source_at_top' : False,    
    # 'navigation_depth': -1,
    # 'collapse_navigation': True,
    'collapse_navigation': False,
    'navigation_depth': -1,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

#from
#https://stackoverflow.com/questions/18969093/how-to-include-the-toctree-in-the-sidebar-of-each-page
# html_sidebars = { '**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html'] }


# html_show_copyright
#
#    If true, “(C) Copyright …” is shown in the HTML footer. Default is True.
#
#    New in version 1.0.

html_show_copyright = False


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'SphinxTest2021doc'
html_title = 'NewHTMLtitle'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'SphinxTest2021.tex', 'Sphinx Test 2021 Documentation',
     'JTester', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'sphinxtest2021', 'Sphinx Test 2021 Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'SphinxTest2021', 'Sphinx Test 2021 Documentation',
     author, 'SphinxTest2021', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
