#baseurl: file:///C:/GitHub/gamepad-coder/gamepad-coder.github.io/_site
collections:
  Philosophy:
    output: true
  App:
    output: true
include: [
"Documentation"
, "Documentation/_static"
, "Documentation/_static/css"
, "Documentation/_static/fonts"
, "Documentation/_static/images"
, "Documentation/_static/js"
]
github: [metadata]
encoding: UTF-8
exclude: [.notes,Documentation/__backup__,Documentation/_Sphinx]
