#baseurl: file:///C:/GitHub/gamepad-coder/gamepad-coder.github.io/_site
collections:
  Philosophy:
    output: true
  App:
    output: true
include: [
"Documentation"
]
github: [metadata]
encoding: UTF-8
exclude: [.notes,desktop.ini,Documentation/__backup__,Documentation/_Sphinx]
